sudo: false
language: node_js
node_js:
  - '8'
preinstall:
script: git --version || npm run build
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - git-core
    packages:
    - g++-4.8
    - git
deploy:
  local_dir: 'dist'
  provider: pages
  skip_cleanup: true
  target_branch: master
  github_token: $GITHUB_TOKEN
  on:
    branch: production